language: node_js
node_js:
  - '12.13.0'
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: 'aY7oM1eSdrigwnVAUaW83sqZHpKmCyRAbEYHS3EPY01NVCHpuZCg9I/FHIKtEUkI4RLi1CtLDlWxmzkDfsodmy5CoAMlOcXre9p/oxMdVuTdMp/G39GOd9nJDvj1xUM09dbFrBgR5q4aP7gFxtuBM52TxjSPLs69Ki1o0vj3B5ZnQMCRmZVMwL9mPPy1yE2qWS7nI+y70ctVch+snn/WZpIvMM7AVrtpRO+6LzBkdsmG+I5yiSUQaH++q2TyPT4ZFdmgDiiu1phPHC1WY3QfQMM/E0s9lLfqUKU+mAo0Qwg5tB77FMTrlfnOwBMWwukpGO4yuYoF+B/pItFoTxhHcoceqvSnolmoJc1cyioGuuvQI8/D3+HMnJxWegPQJp0JF4I2+VGIxQsZQVj4UwQaRGFOv6zvWUMoWYmjfGt0m44kPFJI7QXeAB6t8y7MpH25/pPJq2OUjUHMgaaXOPHbGA2q1uurItHtvW3Lqj1dUm3MkFhSvBmQYznmCK4QPjSpjR/7wM10E7qfFehDBEUsdveCtLjhWIq57bcpZv6rWblXw9IQkLUW9UEQKo13u5YEztLxwrbdUXPXyq11VIGrqTb9OvgqL8e1oQO6irkzc+1QSDMSq99RXNfrfY0WSgtfYPFjCMNPojUzqcOe4w/Ig6OOK0deMs4bT0PHFJQcMcg='
