language: node_js
node_js:
  - '12.13.0'
script:
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project console-devser --token $FIREBASE_TOKEN
