version: 2

references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  prepare_dependencies_and_cache:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: 'Move build to workspace' # Move build into our workspace.
          command: |
            set -exu
            mkdir -p /tmp/workspace/build
            mv ~/project/build/* /tmp/workspace/build
      - persist_to_workspace: # store the built files into the workspace for other jobs.
          root: *workspace_root
          paths:
            - build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Restore Previous Job Assets (build) to the Root Directory.
          command: |
            set -exu
            mkdir -p /tmp/workspace/build
            mkdir -p ~/project/build
            mv /tmp/workspace/build/* ~/project/build/
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_deploy:
    jobs:
      - prepare_dependencies_and_cache
      - build:
          requires:
            - prepare_dependencies_and_cache
      - test:
          requires:
            - prepare_dependencies_and_cache
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
