version: 2.1

jobs:
  prepare_dependencies_and_cache:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
        name: Test
        command: npm test
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
        name: Firebase Deploy
        command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  build_and_test:
    jobs:
      - prepare_dependencies_and_cache
      - build:
        requires:
          - prepare_dependencies_and_cache
      - test:
        requires:
          - prepare_dependencies_and_cache
          - build
  deploy:
    jobs:
      - hold:
        type: approval
        requires:
          - build
          - test
      - deploy:
        requires:
          - hold
