version: 2
references:
  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
jobs:
  prepare_dependencies_and_cache:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace: # store the built files into the workspace for other jobs.
          root: *workspace_root
          paths:
            - modules
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_deploy:
    jobs:
      - prepare_dependencies_and_cache
      - build:
          requires:
            - prepare_dependencies_and_cache
      - test:
          requires:
            - prepare_dependencies_and_cache
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
