name: Bump version
on:
  pull_request:
    branches: master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: remorses/bump-version@js
        with:
          version_file: VERSION
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}
